hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/planetoid/hydra/
setup:
  seed: 20
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/planetoid/
load:
  dataset: cora
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/planetoid/chkpt.pt
  split: public
train:
  epochs: 2000
  patience: 50
  lr : 1e-3
  wd : 0 #1e-8
model:
  hidden_channels: 64
  dropout: 0.6
  max_iter: 20
  tol: 1e-6