hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/snap_amz/hydra/
setup:
  seed: 2333
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/snap_amz/
load:
  split: fixed_06
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/snap_amz/test.pt
train:
  epochs: 2000
  patience: 200
  lr : .008
  wd : 5e-4
model:
  hidden_channels: 16
  dropout: 0.4
  max_iter: 100
  tol: 1e-6